config/routes.rb
Ej::Application.routes.draw do
  authenticated :user do
    root :to => redirect("/admin/products")
    namespace :admin do
      resources :products, :users, :settings, :vendors, :tiers, :inventory, :courier_transits, :fedex_transits, :records
      match "products/add_vendor" => "products#add_vendor"
      match "products/:id/add_watch" => "products#add_watch"
      match "inventory/:id/add_record" => "inventory#add_record"
    end
  end
  root :to => "users#index"
  devise_for :users
end

app/models/tier.rb
class Tier < ActiveRecord::Base
  attr_accessible :cost, :name
end

app/controllers/tiers_controller.rb
class TiersController < ApplicationController
  # GET /tiers
  # GET /tiers.json
  def index
    @tiers = Tier.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @tiers }
    end
  end

  # GET /tiers/1
  # GET /tiers/1.json
  def show
    @tier = Tier.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @tier }
    end
  end

  # GET /tiers/new
  # GET /tiers/new.json
  def new
    @tier = Tier.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @tier }
    end
  end

  # GET /tiers/1/edit
  def edit
    @tier = Tier.find(params[:id])
  end

  # POST /tiers
  # POST /tiers.json
  def create
    @tier = Tier.new(params[:tier])

    respond_to do |format|
      if @tier.save
        format.html { redirect_to @tier, notice: 'Tier was successfully created.' }
        format.json { render json: @tier, status: :created, location: @tier }
      else
        format.html { render action: "new" }
        format.json { render json: @tier.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /tiers/1
  # PUT /tiers/1.json
  def update
    @tier = Tier.find(params[:id])

    respond_to do |format|
      if @tier.update_attributes(params[:tier])
        format.html { redirect_to @tier, notice: 'Tier was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @tier.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tiers/1
  # DELETE /tiers/1.json
  def destroy
    @tier = Tier.find(params[:id])
    @tier.destroy

    respond_to do |format|
      format.html { redirect_to tiers_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/tiers_helper.rb
module TiersHelper
end

app/views/tiers/_form.html.haml
= simple_form_for(@tier) do |f|
  = f.error_notification

  .form-inputs
    = f.input :name
    = f.input :cost

  .form-actions
    = f.button :submit

app/views/tiers/edit.html.haml
%h1 Editing tier

= render 'form'

= link_to 'Show', @tier
\|
= link_to 'Back', tiers_path

app/views/tiers/index.html.haml
%h1 Listing tiers

%table
  %tr
    %th Name
    %th Cost
    %th
    %th
    %th

  - @tiers.each do |tier|
    %tr
      %td= tier.name
      %td= tier.cost
      %td= link_to 'Show', tier
      %td= link_to 'Edit', edit_tier_path(tier)
      %td= link_to 'Destroy', tier, :method => :delete, :data => { :confirm => 'Are you sure?' }

%br

= link_to 'New Tier', new_tier_path

app/views/tiers/new.html.haml
%h1 New tier

= render 'form'

= link_to 'Back', tiers_path

app/views/tiers/show.html.haml
%p#notice= notice

%p
  %b Name:
  = @tier.name
%p
  %b Cost:
  = @tier.cost

= link_to 'Edit', edit_tier_path(@tier)
\|
= link_to 'Back', tiers_path