config/routes.rb
Ej::Application.routes.draw do
  authenticated :user do
    root :to => redirect("/admin/products")
    namespace :admin do
      resources :products, :users, :settings, :vendors, :tiers, :inventory, :courier_transits, :fedex_transits, :records
      match "products/add_vendor" => "products#add_vendor"
      match "products/:id/add_watch" => "products#add_watch"
      match "inventory/:id/add_record" => "inventory#add_record"
    end
  end
  root :to => "users#index"
  devise_for :users
end

app/controllers/inventory_controller.rb
class Admin::InventoryController < ApplicationController
  before_filter :append_view_paths

  def append_view_paths
    append_view_path 'app/views/admin/inventory/record_forms'

  end

  def index
    @products = ProductInstance.all
  end
  def show

    id = params[:id]

    @product_instance = ProductInstance.find(id)
    @history = @product_instance.history()
    @d = CourierTransit.new()
  #  @debug.bin_number = 5423
    @d.product_id = params[:id]
    @d.is_signature_required  = true
    @d.table = @d.class.name.tableize;

    @f = FedexTransit.new()
  #  @debug.bin_number = 5423
    @f.product_id = params[:id]
    @f.table = @f.class.name.tableize;
  end
  def add_record
    prdouct_id = params[:id]
  end
end

app/views/admin/inventory/index.html.haml
%table
  %thead
    %th Product Id
    %th Bin Id
    %th Model
    %th Brand
    %th Tier
    %th Last Rotation
  = render @products

app/views/admin/inventory/show.html.haml
erwda
= render :partial =>  '/courier_transit'
= render :partial => '/fedex_transit'

-@next = @product_instance.next_record()
=debug @next
%div{:id=>'history'}
  -@history.each do |r|
    %p{:id=>'record-'+r.id}
      =r.product_id
      =link_to 'Destroy', admin_records_path+'/'+r.id,
                  :confirm => 'Are you sure?', :method => :delete, 'data-action'=>'destroy'