config/routes.rb
Ej::Application.routes.draw do
  authenticated :user do
    root :to => redirect("/admin/products")
    namespace :admin do
      resources :products, :users, :settings, :vendors, :tiers, :inventory, :courier_transits, :fedex_transits, :records
      match "products/add_vendor" => "products#add_vendor"
      match "products/:id/add_watch" => "products#add_watch"
      match "inventory/:id/add_record" => "inventory#add_record"
    end
  end
  root :to => "users#index"
  devise_for :users
end

app/models/product.rb
class Product < ActiveRecord::Base
  belongs_to :tier
  belongs_to :vendor
  attr_accessible :brand, :case, :color, :description, :material, :model, :msrp, :style, :vendor_id, :quantity
end

app/controllers/products_controller.rb
class Admin::ProductsController < ApplicationController
  before_filter :user_preferences
  def user_preferences
    key = 'admin::'+ (current_user.id.to_s)
    stored = $redis.get(key)
    @admin_prefs = stored ? JSON.parse(stored) :  {}
    if params[:sort]
      @admin_prefs['product_sort'] = params[:sort] + " " + (params[:order] == '1' ? 'ASC': 'DESC')
    end
    if params['page_size']
      @admin_prefs['page_size'] = params['page_size']
    end
    if params[:prefs]
      $redis.set(key, @admin_prefs.to_json)
    end
    @order = @admin_prefs['product_sort'] || "model"
    @page_size = @admin_prefs['page_size'].to_i || 10;
  end
  def index
    @products = Product.order(@order).page(params[:page]).per(@page_size)
  end
  def edit
    @product = Product.find(params[:id])
    model_id = sprintf '%05d', params[:id]
    @product_instances = ProductInstance.where('id ~ ?','^'+model_id)
    render "admin/products/create_edit"
  end
  def new
    @product = Product.new()
    @product_instances = []
    render "admin/products/create_edit"
  end
  def create
    product = Product.new(params[:product])
    product.save()
    redirect_to admin_products_path
  end
  def update
    product = Product.find(params[:id])
    if product.update_attributes params[:product]
      redirect_to admin_products_path
    else
      render :action => :edit
    end
  end
  def add_watch
    instance = ProductInstance.new
    model_id = sprintf '%05d', params[:id]
    product_id = ProductInstance.where('id ~ ?','^'+model_id).count + 1
    instance.id = "#{model_id}-#{product_id}"
    instance.save
    render :json => {:id=> instance.id}
  end
end

app/views/admin/products/_product.html.haml
%tr
  %td
    = product.model
    %td
      = product.brand
    %td
      = link_to 'edit', edit_admin_product_path(product.id)
    %td

app/views/admin/products/_vendor.html.haml
%div
  =simple_form_for :vendor, :html => {:id => 'add_vendor'}, :url => '/users'  do |f|
    =f.text_field :name, placeholder: 'name', class: "required"
    =f.text_field :address, placeholder: 'address', class: "required"
    =f.text_field :phone, placeholder: 'phone', class: "required phoneUS"
    =f.text_field :email, placeholder: 'email', class: "required email"
    =f.text_field :website, placeholder: 'website', class: "required url"
    %button{class: "cancel"}
      Cancel
    = f.submit 'Add Vendor'

app/views/admin/products/add_vendor.js.erb
$('<div class="modal hide fade"><%=render("vendor").squish.html_safe -%></div>').modal({backdrop:false});


$('#add_vendor').submit(function(){
    var data = $(this).serialize();
    $.ajax({
        type: "POST",
        url: "/admin/vendors",
        data: $(this).serialize(),
        success: function(response){
            $("#product_vendor").append('<option value="'+response.id+'">'+response.name+'</option>')
                .trigger("liszt:updated")
            $('.modal').hide();
        },
        error: function(){
            alert("An unexpected error has occurred")
        },
        dataType:'json'
    });
    return false;
}).validate()

app/views/admin/products/create_edit.html.haml
= javascript_include_tag "//cdnjs.cloudflare.com/ajax/libs/chosen/0.9.12/chosen.jquery.min.js"
= stylesheet_link_tag "//cdn.jsdelivr.net/chosen/0.9.11/chosen.css"
= javascript_include_tag "//cdnjs.cloudflare.com/ajax/libs/jquery-validate/1.11.0/jquery.validate.min.js"

#sub_navigation= render_navigation
HOLA!!!

= simple_form_for [:admin, @product] do |f|
  = f.input :quantity
  = f.input :model
  = f.input :brand
  = f.input :material
  = f.input :style
  = f.input :color
  = f.input :case
  = f.input :msrp
  %label
    Vendor
  = f.collection_select "vendor_id", Vendor.all, :id, :name, :label => "Name"
  = f.input :description
  = f.button :submit

%table{:id=>'product_instances'}
  - @product_instances.each do |product_instance|
    %tr
      %td
        = product_instance.id

%button{:id=>"add-watch"} Add Watch

%div{:class=>"modal hide fade"}
  = render("vendor").squish.html_safe

app/views/admin/products/index.html.haml
#sub_navigation= render_navigation
%h3 Home
%h2 Products
%script{:src=>"//cdnjs.cloudflare.com/ajax/libs/chosen/0.9.12/chosen.jquery.min.js"}
%link{:rel=>"stylesheet", :href => "//cdn.jsdelivr.net/chosen/0.9.11/chosen.css"}

= simple_form_for :preference do |f|
  = f.select :page_size, [10,20,50], :selected => @admin_prefs['page_size']

%div{:id=>"paginator"}
  = paginate @products, :remote => true



%table

  %thead
    %th
      = link_to 'Model', admin_products_path+'?&prefs=1&sort=model&order=-1',  {:id => 'model_sort'}
    %th
      = link_to 'Brand', admin_products_path+'?&prefs=1&sort=brand&order=-1', {:id => 'brand_sort'}
    %th
      = link_to 'Tier', admin_products_path+'?&prefs=1&sort=tier&order=-1', {:id => 'tier_sort'}
    %th
  %tbody{:id=>"products"}
    = render @products

app/views/admin/products/index.js.erb
$('#products').html('<%=escape_javascript render(@products)%>');
$('#paginator').html('<%= escape_javascript(paginate(@products, :remote => true).to_s) %>');

app/views/admin/products/show.html.haml
#sub_navigation= render_navigation